#host url
https://


#curl options
--slient
#include response header
#--include
#to ignore SSL when working with localhost
#--insecure
#to read a header(s) from a file. file format should be like:
#Header-Name: Header-Value
#e.g Authorization: YOUR_AUTH_TOKEN_HERE
#-H @/path/to/file.txt


# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json;
User-Agent: VRC

# query
GET /anything

#body
# {
#     "test": 123
# }
